/**
 * Test config, deliberately separate from vite.config.ts.
 *
 * vite.config.ts wraps @lovable.dev/vite-tanstack-config, which bundles TanStack Start,
 * nitro, the SPA prerender and the dev-only component tagger — none of which a unit test
 * needs, and several of which do not run outside a real build. Vitest prefers this file
 * when it exists, so the app config is left untouched rather than conditionally patched.
 *
 * React is the only plugin tests actually need. The `@/` alias comes from resolve.
 * tsconfigPaths, which Vite 8 supports natively — the vite-tsconfig-paths plugin the app
 * config uses is redundant here and warns about exactly that.
 */
import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  resolve: { tsconfigPaths: true },
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: ["./src/test/setup.ts"],
    include: ["src/**/*.test.{ts,tsx}"],
    coverage: {
      provider: "v8",
      reporter: ["text", "lcov"],
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        // Generated by the shadcn CLI and by TanStack Router — vendored, not authored here.
        "src/components/ui/**",
        "src/routeTree.gen.ts",
        // Build entrypoints: exercised by `vite build`, not reachable from jsdom.
        "src/server.ts",
        "src/start.ts",
        "src/router.tsx",
        "src/**/*.test.{ts,tsx}",
        "src/test/**",
      ],
      // Lines and functions are pinned at exactly 100 because that is where the suite sits:
      // a new component with an untested handler should fail the build rather than quietly
      // dilute the average. Statements and branches sit just under their real values
      // (99.5 / 95.32) — the shortfall is defensive `?? 0` fallbacks that only a malformed
      // API response would reach, so demanding 100 there would mean writing tests for
      // responses the server cannot send.
      thresholds: {
        statements: 99,
        branches: 94,
        functions: 100,
        lines: 100,
      },
    },
  },
});
