/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SquadRouteImport } from './routes/squad'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GamesRouteImport } from './routes/games'
import { Route as EvalRouteImport } from './routes/eval'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UploadIndexRouteImport } from './routes/upload.index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as UploadReviewRouteImport } from './routes/upload.review'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadRoute = SquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalRoute = EvalRouteImport.update({
  id: '/eval',
  path: '/eval',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadIndexRoute = UploadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UploadRoute,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRoute,
} as any)
const UploadReviewRoute = UploadReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => UploadRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => GamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/eval': typeof EvalRoute
  '/games': typeof GamesRouteWithChildren
  '/login': typeof LoginRoute
  '/players': typeof PlayersRoute
  '/roster': typeof RosterRoute
  '/settings': typeof SettingsRoute
  '/squad': typeof SquadRoute
  '/teams': typeof TeamsRoute
  '/upload': typeof UploadRouteWithChildren
  '/games/$gameId': typeof GamesGameIdRoute
  '/join/$token': typeof JoinTokenRoute
  '/upload/review': typeof UploadReviewRoute
  '/games/': typeof GamesIndexRoute
  '/upload/': typeof UploadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/eval': typeof EvalRoute
  '/login': typeof LoginRoute
  '/players': typeof PlayersRoute
  '/roster': typeof RosterRoute
  '/settings': typeof SettingsRoute
  '/squad': typeof SquadRoute
  '/teams': typeof TeamsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/join/$token': typeof JoinTokenRoute
  '/upload/review': typeof UploadReviewRoute
  '/games': typeof GamesIndexRoute
  '/upload': typeof UploadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/eval': typeof EvalRoute
  '/games': typeof GamesRouteWithChildren
  '/login': typeof LoginRoute
  '/players': typeof PlayersRoute
  '/roster': typeof RosterRoute
  '/settings': typeof SettingsRoute
  '/squad': typeof SquadRoute
  '/teams': typeof TeamsRoute
  '/upload': typeof UploadRouteWithChildren
  '/games/$gameId': typeof GamesGameIdRoute
  '/join/$token': typeof JoinTokenRoute
  '/upload/review': typeof UploadReviewRoute
  '/games/': typeof GamesIndexRoute
  '/upload/': typeof UploadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/eval'
    | '/games'
    | '/login'
    | '/players'
    | '/roster'
    | '/settings'
    | '/squad'
    | '/teams'
    | '/upload'
    | '/games/$gameId'
    | '/join/$token'
    | '/upload/review'
    | '/games/'
    | '/upload/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/eval'
    | '/login'
    | '/players'
    | '/roster'
    | '/settings'
    | '/squad'
    | '/teams'
    | '/games/$gameId'
    | '/join/$token'
    | '/upload/review'
    | '/games'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/eval'
    | '/games'
    | '/login'
    | '/players'
    | '/roster'
    | '/settings'
    | '/squad'
    | '/teams'
    | '/upload'
    | '/games/$gameId'
    | '/join/$token'
    | '/upload/review'
    | '/games/'
    | '/upload/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  EvalRoute: typeof EvalRoute
  GamesRoute: typeof GamesRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlayersRoute: typeof PlayersRoute
  RosterRoute: typeof RosterRoute
  SettingsRoute: typeof SettingsRoute
  SquadRoute: typeof SquadRoute
  TeamsRoute: typeof TeamsRoute
  UploadRoute: typeof UploadRouteWithChildren
  JoinTokenRoute: typeof JoinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squad': {
      id: '/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof SquadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eval': {
      id: '/eval'
      path: '/eval'
      fullPath: '/eval'
      preLoaderRoute: typeof EvalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/': {
      id: '/upload/'
      path: '/'
      fullPath: '/upload/'
      preLoaderRoute: typeof UploadIndexRouteImport
      parentRoute: typeof UploadRoute
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/upload/review': {
      id: '/upload/review'
      path: '/review'
      fullPath: '/upload/review'
      preLoaderRoute: typeof UploadReviewRouteImport
      parentRoute: typeof UploadRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof GamesRoute
    }
  }
}

interface GamesRouteChildren {
  GamesGameIdRoute: typeof GamesGameIdRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesGameIdRoute: GamesGameIdRoute,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface UploadRouteChildren {
  UploadReviewRoute: typeof UploadReviewRoute
  UploadIndexRoute: typeof UploadIndexRoute
}

const UploadRouteChildren: UploadRouteChildren = {
  UploadReviewRoute: UploadReviewRoute,
  UploadIndexRoute: UploadIndexRoute,
}

const UploadRouteWithChildren =
  UploadRoute._addFileChildren(UploadRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  EvalRoute: EvalRoute,
  GamesRoute: GamesRouteWithChildren,
  LoginRoute: LoginRoute,
  PlayersRoute: PlayersRoute,
  RosterRoute: RosterRoute,
  SettingsRoute: SettingsRoute,
  SquadRoute: SquadRoute,
  TeamsRoute: TeamsRoute,
  UploadRoute: UploadRouteWithChildren,
  JoinTokenRoute: JoinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
