export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          appleid: string;
          email: string | null;
          name: string | null;
          role: string;
          createdat: string;
          updatedat: string;
        };
        Insert: {
          id?: string;
          appleid: string;
          email?: string | null;
          name?: string | null;
          role?: string;
          createdat?: string;
          updatedat?: string;
        };
        Update: {
          id?: string;
          appleid?: string;
          email?: string | null;
          name?: string | null;
          role?: string;
          createdat?: string;
          updatedat?: string;
        };
      };
      games: {
        Row: {
          id: string;
          date: string;
          hometeam: string;
          awayteam: string;
          homescore: number;
          awayscore: number;
          screenshoturl: string | null;
          processed: boolean;
          userid: string;
          createdat: string;
          updatedat: string;
        };
        Insert: {
          id?: string;
          date: string;
          hometeam: string;
          awayteam: string;
          homescore: number;
          awayscore: number;
          screenshoturl?: string | null;
          processed?: boolean;
          userid: string;
          createdat?: string;
          updatedat?: string;
        };
        Update: {
          id?: string;
          date?: string;
          hometeam?: string;
          awayteam?: string;
          homescore?: number;
          awayscore?: number;
          screenshoturl?: string | null;
          processed?: boolean;
          userid?: string;
          createdat?: string;
          updatedat?: string;
        };
      };
      players: {
        Row: {
          id: string;
          name: string;
          team: string;
          teammategrade: string | null;
          gameidfromfile: string;
          playerid: string;
          position: string;
          points: number;
          rebounds: number;
          assists: number;
          steals: number;
          blocks: number;
          turnovers: number;
          fouls: number;
          fgmade: number;
          fgattempted: number;
          threemade: number;
          threeattempted: number;
          ftmade: number;
          ftattempted: number;
          gameid: string;
          userid: string;
          createdat: string;
          updatedat: string;
        };
        Insert: {
          id?: string;
          name: string;
          team: string;
          teammategrade?: string | null;
          gameidfromfile: string;
          playerid: string;
          position: string;
          points?: number;
          rebounds?: number;
          assists?: number;
          steals?: number;
          blocks?: number;
          turnovers?: number;
          fouls?: number;
          fgmade?: number;
          fgattempted?: number;
          threemade?: number;
          threeattempted?: number;
          ftmade?: number;
          ftattempted?: number;
          gameid: string;
          userid: string;
          createdat?: string;
          updatedat?: string;
        };
        Update: {
          id?: string;
          name?: string;
          team?: string;
          teammategrade?: string | null;
          gameidfromfile?: string;
          playerid?: string;
          position?: string;
          points?: number;
          rebounds?: number;
          assists?: number;
          steals?: number;
          blocks?: number;
          turnovers?: number;
          fouls?: number;
          fgmade?: number;
          fgattempted?: number;
          threemade?: number;
          threeattempted?: number;
          ftmade?: number;
          ftattempted?: number;
          gameid?: string;
          userid?: string;
          createdat?: string;
          updatedat?: string;
        };
      };
      player_stats: {
        Row: {
          id: string;
          name: string;
          team: string;
          teammategrade: string | null;
          points: number;
          rebounds: number;
          assists: number;
          steals: number;
          blocks: number;
          turnovers: number;
          fouls: number;
          fgmade: number;
          fgattempted: number;
          threemade: number;
          threeattempted: number;
          ftmade: number;
          ftattempted: number;
          gameid: string;
          userid: string;
          createdat: string;
          updatedat: string;
        };
        Insert: {
          id?: string;
          name: string;
          team: string;
          teammategrade?: string | null;
          points?: number;
          rebounds?: number;
          assists?: number;
          steals?: number;
          blocks?: number;
          turnovers?: number;
          fouls?: number;
          fgmade?: number;
          fgattempted?: number;
          threemade?: number;
          threeattempted?: number;
          ftmade?: number;
          ftattempted?: number;
          gameid: string;
          userid: string;
          createdat?: string;
          updatedat?: string;
        };
        Update: {
          id?: string;
          name?: string;
          team?: string;
          teammategrade?: string | null;
          points?: number;
          rebounds?: number;
          assists?: number;
          steals?: number;
          blocks?: number;
          turnovers?: number;
          fouls?: number;
          fgmade?: number;
          fgattempted?: number;
          threemade?: number;
          threeattempted?: number;
          ftmade?: number;
          ftattempted?: number;
          gameid?: string;
          userid?: string;
          createdat?: string;
          updatedat?: string;
        };
      };
    };
  };
}
